const boardIndexs = {
    a:{1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0},
    b:{1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0},
    c:{1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0},
    d:{1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0},
    e:{1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0},
    f:{1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0},
    g:{1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0},
    h:{1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0},
    i:{1:0,2:0,3:0,4:0,5:0,6:0,7:0,8:0,9:0}	
}

const xYIndexes = {
    x: [1,2,3,4,5,6,7,8,9],
    y:['a','b','c','d','e','f','g','h','i'],
}

const groupIndexes={
    1: {
        x: [1,2,3],
        y: ['a','b','c']
    },
    2: {
        x:[4,5,6],
        y: ['a','b','c']
    },
    3: {
        x:[7,8,9],
        y: ['a','b','c']
    },
    4: {
        x:[1,2,3],
        y:['d','e','f']
    },
    5: {
        x:[4,5,6],
        y:['d','e','f']
    },
    6: {
        x:[7,8,9],
        y:['d','e','f']
    },
    7: {
        x:[1,2,3],
        y:['h','i','j']
    },
    8: {
        x:[4,5,6],
        y:['h','i','j']
    },
    9: {
        x:[7,8,9],
        y:['h','i','j']
    }

}

const groups ={
    1 : {
        a:{
            1:{
                v:0,
                e:null,
            },
            2:{
                v:0,
                e:null,
            },
            3:{
              v:0,
              e:null,
            }
        },
        b:{
            1:{
                v:0,
                e:null,
            },
            2:{
                v:0,
                e:null,
            },
            3:{
              v:0,
              e:null,
            }           
        },
        c:{
            1:{
                v:0,
                e:null,
            },
            2:{
                v:0,
                e:null,
            },
            3:{
              v:0,
              e:null,
            }
        }
    },
    2 :{
        a:{
            4:{
                v:0,
                e:null,
            },
            5:{
                v:0,
                e:null,
            },
            6:{
                v:0,
                e:null,
            }
        },
        b:{
            4:{
                v:0,
                e:null,
            },
            5:{
                v:0,
                e:null,
            },
            6:{
                v:0,
                e:null,
            }
        },
        c:{
            4:{
                v:0,
                e:null,
            },
            5:{
                v:0,
                e:null,
            },
            6:{
                v:0,
                e:null,
            }
        }
    },
    3:{
        a:{
            7:{
                v:0,
                e:null,
            },
            8:{
                v:0,
                e:null,
            },
            9:{
                v:0,
                e:null,
            }
        },
        b:{
            7:{
                v:0,
                e:null,
            },
            8:{
                v:0,
                e:null,
            },
            9:{
                v:0,
                e:null,
            }
        },
        c:{
            7:{
                v:0,
                e:null,
            },
            8:{
                v:0,
                e:null,
            },
            9:{
                v:0,
                e:null,
            }
        }			
    },
    4 : {
        d:{
            1:{
                v:0,
                e:null,
            },
            2:{
                v:0,
                e:null,
            },
            3:{
                v:0,
                e:null,
            }
        },
        e:{
            1:{
                v:0,
                e:null,
            },
            2:{
                v:0,
                e:null,
            },
            3:{
                v:0,
                e:null,
            }
        },
        f:{
            1:{
                v:0,
                e:null,
            },
            2:{
                v:0,
                e:null,
            },
            3:{
                v:0,
                e:null,
            }
        },
    },
    5 : {
        d:{
            4:{
                v:0,
                e:null,
            },
            5:{
                v:0,
                e:null,
            },
            6:{
                v:0,
                e:null,
            }
        },
        e:{
            4:{
                v:0,
                e:null,
            },
            5:{
                v:0,
                e:null,
            },
            6:{
                v:0,
                e:null,
            }
        },
        f:{
            4:{
                v:0,
                e:null,
            },
            5:{
                v:0,
                e:null,
            },
            6:{
                v:0,
                e:null,
            }
        }				
    },
    6:{	
        d:{
            7:{
                v:0,
                e:null,
            },
            8:{
                v:0,
                e:null,
            },
            9:{
                v:0,
                e:null,
            }
        },
        e:{
            7:{
                v:0,
                e:null,
            },
            8:{
                v:0,
                e:null,
            },
            9:{
                v:0,
                e:null,
            }
        },
        f:{
            7:{
                v:0,
                e:null,
            },
            8:{
                v:0,
                e:null,
            },
            9:{
                v:0,
                e:null,
            }
        }
    },
    7:{
        g:{
            1:{
                v:0,
                e:null,
            },
            2:{
                v:0,
                e:null,
            },
            3:{
                v:0,
                e:null,
            }
        },
        h:{
            1:{
                v:0,
                e:null,
            },
            2:{
                v:0,
                e:null,
            },
            3:{
                v:0,
                e:null,
            }
        },
        i:{
            1:{
                v:0,
                e:null,
            },
            2:{
                v:0,
                e:null,
            },
            3:{
                v:0,
                e:null,
            }
        }
    },
    8:{
        g:{
            4:{
                v:0,
                e:null,
            },
            5:{
                v:0,
                e:null,
            },
            6:{
                v:0,
                e:null,
            }
        },
        h:{
            4:{
                v:0,
                e:null,
            },
            5:{
                v:0,
                e:null,
            },
            6:{
                v:0,
                e:null,
            }
        },
        i:{
            4:{
                v:0,
                e:null,
            },
            5:{
                v:0,
                e:null,
            },
            6:{
                v:0,
                e:null,
            }
        }			
    },
    9:{
        g:{
            7:{
                v:0,
                e:null,
            },
            8:{
                v:0,
                e:null,
            },
            9:{
                v:0,
                e:null,
            }
        },
        h:{
            7:{
                v:0,
                e:null,
            },
            8:{
                v:0,
                e:null,
            },
            9:{
                v:0,
                e:null,
            }
        },
        i:{            
            7:{
                v:0,
                e:null,
            },
            8:{
                v:0,
                e:null,
            },
            9:{
                v:0,
                e:null,
            }
        }				
    }
}

export {
    boardIndexs,
    groupIndexes,
    xYIndexes,
    groups
};